### ISSUE TITLE
Not possible to set status on an issue

### ISSUE THREAD

**Issue by foobar-1337** [Chavaillaz/jira-client#2]
Hi,

The setting of a new status doesn't seem to work? The status is unchanged in Jira.

I have extracted a status-object by calling:
`jiraClient.getProjectApi().getProjectStatuses(projectKey)`

This method return an array of issueTypes. For the current issyeType ("Bug"), I'm extracting one of the Status-objects ("To Do") and passing it to this code:

```
final var updateIssue = Issue.fromKey(jiraIssueKey);
updateIssue.getFields().setStatus(status); // This is the extracted status-object.
jiraClient.getIssueApi().updateIssue(updateIssue);
```

I'm using Jira v.9.3.1 (standalone)

**Comment by Chavjoh** [comment]
Hi,

Indeed unfortunately the way Jira is working does not allow direct update of status from the issue itself, but requires a transition:
```
jiraClient.getIssueApi().doTransition(jiraIssueKey, IssueTransition.fromId("1"))
```
The identifiers of the allowed transitions for an issue can be found with the following call:
```
jiraClient.getIssueApi().getTransitions(jiraIssueKey)
```

Hope this helps :)

**Comment by foobar-1337** [comment]
Thanks for the clarification! :-)
