### ISSUE TITLE
doTransition does not allow updating fields

### ISSUE THREAD

**Issue by bertrand-lorentz** [Chavaillaz/jira-client#4]
The Jira REST API allows you to update fields as part of a transition (see https://developer.atlassian.com/cloud/jira/platform/rest/v3/api-group-issues/#api-rest-api-3-issue-issueidorkey-transitions-post).
But the "doTransition" method does not expose this.

For most cases this is not a problem, you can just edit the issue.

But my Jira instance is configured so that the "Resolution" field is not modifiable when editing the issue, and it **must** be set as part of the transition to "Resolved" or "Closed" (it is mandatory in the UI screen for the transition, with a default value preselected).

So if I use "doTransition" to transition to "Resolved" or "Closed", the resolution will always be set to its default value "Fixed", and I cannot modify it anymore.

Calling the REST API directly with the following body allows me to set the resolution as part of the transition:

```JSON
{
  "transition": {
   "id": "491"
  },
  "fields": {
    "resolution": {
        "name": "Won't Fix"
      }
  }
}
```

**Comment by Chavjoh** [comment]
Thanks again for your issue and pull request, I added a generic type for the `fields` attribute and you can now perform, for example, the resolution update while doing a transition using the following code:

```
IssueTransition<Fields> closeTransition = IssueTransition.fromId("1234");
closeTransition.getFields().setResolution(Resolution.fromName("Won't Fix"));
client.getIssueApi().doTransition(issueId, closeTransition).join();
```

In case you have specific custom fields to also edit, it can be done as the example below:

```
CompanyFields fields = new CompanyFields();
fields.setResolution(Resolution.fromName("Won't Fix"));
fields.setYourCustomField("Your Custom Value");

IssueTransition<CompanyFields> closeTransition = new IssueTransition<>();
closeTransition.setTransition(Transition.fromId("1234"));
closeTransition.setFields(fields);

client.getIssueApi().doTransition(issueId, closeTransition).get();
```

The package is released in Maven Central but it will take some hours to be fully synchronized and usable.

**Comment by bertrand-lorentz** [comment]
Thanks for the quick reaction and release ! It works well for me.
Good point on the generic type for fields. I'm using this feature for some of our custom fields, but I didn't need to set those fields for a transition, so I hadn't thought about it for my PR.
